// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nostos.Backend.Data;

#nullable disable

namespace Nostos.Backend.Migrations
{
    [DbContext(typeof(NostosDbContext))]
    partial class NostosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Nostos.Backend.Data.Models.AiProviderSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbeddingApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EmbeddingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbeddingModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LlmEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LlmModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("SttApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SttBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SttEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SttModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiProviderSettings", t =>
                        {
                            t.HasCheckConstraint("CK_AiProviderSettings_SingletonId", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.AssistantSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptureProcessingMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssistantSettings", t =>
                        {
                            t.HasCheckConstraint("CK_AssistantSettings_SingletonId", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BackupRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeBookFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalArchivePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackupRecords");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookAcquisitionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedExtension")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightsStatement")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("ProviderId", "ExternalId", "AssetId")
                        .IsUnique();

                    b.ToTable("BookAcquisitions");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookCollectionModel", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("BookCollections");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAsin")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedIsbn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("NormalizedAsin")
                        .IsUnique()
                        .HasFilter("\"NormalizedAsin\" IS NOT NULL");

                    b.HasIndex("NormalizedIsbn")
                        .IsUnique()
                        .HasFilter("\"NormalizedIsbn\" IS NOT NULL");

                    b.HasIndex("Title");

                    b.HasIndex("WorkId");

                    b.ToTable("Books");

                    b.HasDiscriminator<string>("BookType").HasValue("BookModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.LibraryCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("LibraryCommandReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_LibraryCommandReceipts_Bounds", "length(\"ClientId\") <= 64 AND length(\"IdempotencyKey\") <= 128 AND length(\"CommandKind\") <= 32 AND length(\"ResponseJson\") <= 131072");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.LibraryState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("SingletonSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SingletonSlot")
                        .IsUnique();

                    b.ToTable("LibraryStates", t =>
                        {
                            t.HasCheckConstraint("CK_LibraryStates_SingletonSlot", "\"SingletonSlot\" = 1");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationChunkReceiptRecord", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OffsetBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "ChunkIndex");

                    b.ToTable("MigrationChunkReceiptRecords", t =>
                        {
                            t.HasCheckConstraint("CK_MigrationChunkReceiptRecords_Bounds", "\"ChunkIndex\" >= 0 AND \"OffsetBytes\" >= 0 AND \"LengthBytes\" > 0");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationExportArtifactRecord", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AvailableAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId");

                    b.HasIndex("State", "ExpiresAtUtc");

                    b.ToTable("MigrationExportArtifactRecords");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationJobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationRevision")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationLeaseToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedImportMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreparedStagingId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProgressBytesProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressCompletedChunks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPhase")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProgressTotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressTotalChunks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecoveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReservedStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("State", "LeaseExpiresAtUtc");

                    b.ToTable("MigrationJobRecords", t =>
                        {
                            t.HasCheckConstraint("CK_MigrationJobRecords_AttemptNumber", "\"AttemptNumber\" >= 1");

                            t.HasCheckConstraint("CK_MigrationJobRecords_IdempotencyKey", "length(\"IdempotencyKey\") > 0 AND length(\"IdempotencyKey\") <= 128");

                            t.HasCheckConstraint("CK_MigrationJobRecords_LeaseToken", "\"MigrationLeaseToken\" IS NULL OR (length(\"MigrationLeaseToken\") > 0 AND length(\"MigrationLeaseToken\") <= 128)");

                            t.HasCheckConstraint("CK_MigrationJobRecords_ReservedStorageBytes", "\"ReservedStorageBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIdentitySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileIdentitySizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("JobId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("JobId", "State");

                    b.ToTable("MigrationSessionRecords", t =>
                        {
                            t.HasCheckConstraint("CK_MigrationSessionRecords_ChunkSize", "\"ChunkSize\" >= 4194304 AND \"ChunkSize\" <= 67108864");

                            t.HasCheckConstraint("CK_MigrationSessionRecords_FileIdentitySize", "\"FileIdentitySizeBytes\" = \"TotalBytes\"");

                            t.HasCheckConstraint("CK_MigrationSessionRecords_ReceivedBytes", "\"ReceivedBytes\" >= 0 AND \"ReceivedBytes\" <= \"TotalBytes\"");

                            t.HasCheckConstraint("CK_MigrationSessionRecords_TotalBytes", "\"TotalBytes\" > 0");

                            t.HasCheckConstraint("CK_MigrationSessionRecords_TotalChunks", "\"TotalChunks\" > 0");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationStorageReservationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaimedJobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("MaterializedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReservedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("MigrationStorageReservations");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("NoteCommandReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_NoteCommandReceipts_Bounds", "length(\"ClientId\") <= 64 AND length(\"IdempotencyKey\") <= 128 AND length(\"Command\") <= 32 AND length(\"ResultJson\") <= 131072");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("NoteImportBatches");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteImportBatchNote", b =>
                {
                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("NoteImportBatchNotes");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteImportBookLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("Source", "SourceKey")
                        .IsUnique();

                    b.ToTable("NoteImportBookLinks");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AnchorVerified")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptureSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("text");

                    b.Property<string>("CfiRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("verbatim");

                    b.Property<string>("RawContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAnchorKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("unknown");

                    b.Property<string>("SourceAnchorValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteTopicModel", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("NoteTopics");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.ProviderPreferenceModel", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProviderId");

                    b.ToTable("ProviderPreferences", t =>
                        {
                            t.HasCheckConstraint("CK_ProviderPreferences_ProviderId", "length(\"ProviderId\") > 0 AND length(\"ProviderId\") <= 32");
                        });
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.TopicModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Topic")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WorkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAuthor")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAuthor");

                    b.HasIndex("NormalizedTitle");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Writings");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingNoteModel", b =>
                {
                    b.Property<Guid>("WritingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("WritingId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("WritingNotes");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.AudioBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Asin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Narrator")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("audiobook");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.EBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ebook");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.PhysicalBookModel", b =>
                {
                    b.HasBaseType("Nostos.Backend.Data.Models.BookModel");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.ToTable("Books", t =>
                        {
                            t.Property("Isbn")
                                .HasColumnName("PhysicalBookModel_Isbn");

                            t.Property("PageCount")
                                .HasColumnName("PhysicalBookModel_PageCount");
                        });

                    b.HasDiscriminator().HasValue("physical");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookAcquisitionModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithOne("Acquisition")
                        .HasForeignKey("Nostos.Backend.Data.Models.BookAcquisitionModel", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookCollectionModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithMany("BookCollections")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nostos.Backend.Data.Models.CollectionModel", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.WorkModel", "Work")
                        .WithMany("Books")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nostos.Backend.Data.Models.BookMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("BookModelId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Categories")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Edition")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Editor")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Language")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PlaceOfPublication")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PublishedDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Publisher")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Series")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Subtitle")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Translator")
                                .HasColumnType("TEXT");

                            b1.Property<string>("VolumeNumber")
                                .HasColumnType("TEXT");

                            b1.HasKey("BookModelId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");
                        });

                    b.OwnsOne("Nostos.Backend.Data.Models.FileInfoDetails", "FileDetails", b1 =>
                        {
                            b1.Property<Guid>("BookModelId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ChaptersJson")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CoverFileName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileName")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("HasFile")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LocationsJson")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TracksJson")
                                .HasColumnType("TEXT");

                            b1.HasKey("BookModelId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");
                        });

                    b.OwnsOne("Nostos.Backend.Data.Models.ReadingProgress", "Progress", b1 =>
                        {
                            b1.Property<Guid>("BookModelId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("FinishedAt")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsFavorite")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LastLocation")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("LastReadAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonalReview")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ProgressPercent")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Rating")
                                .HasColumnType("INTEGER");

                            b1.HasKey("BookModelId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookModelId");
                        });

                    b.Navigation("FileDetails")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Progress")
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.CollectionModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationChunkReceiptRecord", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.MigrationSessionRecord", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationExportArtifactRecord", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.MigrationJobRecord", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.MigrationSessionRecord", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.MigrationJobRecord", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteImportBatchNote", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.NoteImportBatch", "Batch")
                        .WithMany("Notes")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nostos.Backend.Data.Models.NoteModel", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteImportBookLink", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.BookModel", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteTopicModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.NoteModel", "Note")
                        .WithMany("NoteTopics")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nostos.Backend.Data.Models.TopicModel", "Topic")
                        .WithMany("NoteTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.WritingModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingNoteModel", b =>
                {
                    b.HasOne("Nostos.Backend.Data.Models.NoteModel", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nostos.Backend.Data.Models.WritingModel", "Writing")
                        .WithMany()
                        .HasForeignKey("WritingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Writing");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.BookModel", b =>
                {
                    b.Navigation("Acquisition");

                    b.Navigation("BookCollections");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.CollectionModel", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteImportBatch", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.NoteModel", b =>
                {
                    b.Navigation("NoteTopics");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.TopicModel", b =>
                {
                    b.Navigation("NoteTopics");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WorkModel", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Nostos.Backend.Data.Models.WritingModel", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
